// web-client/src/components/auth/CodeInput.solid.tsx
/** @jsxImportSource solid-js */
// CodeInput — ввод кода подтверждения единым полем. Порт tweb
// `components/codeInputField.tsx` (291 строка) — У ЭТОГО ФАЙЛА ОРИГИНАЛ УЖЕ
// НА SOLID (единственный из четырёх полей задачи 4), поэтому здесь настоящий
// порт 1:1 движка выбора/подсветки ячеек (`CodeInputField`, tweb :60-291), а
// не перевод с React.
//
// ОДИН невидимый <input inputmode=numeric autocomplete=one-time-code> absolute
// поверх ряда отрисованных ячеек. Вставка строки из N цифр из буфера заполняет
// всё; автозаполнение из SMS работает. Подсветка ячейки считается по
// `selectionStart/selectionEnd`: инпут принудительно держит выделение шириной
// в один символ (`setSelectionRange(start, end, direction)`), поэтому стрелки
// двигают рамку по ячейкам, а Shift+стрелки выделяют несколько. Каретка
// рисуется только в режиме дописывания (`isInserting`) и только в ячейке за
// последней цифрой.
//
// ── Что снято против tweb `CodeInputFieldCompat` (класс-обёртка, :7-58) ─────
// Не портирована. Она существовала ТОЛЬКО затем, чтобы дать ИМПЕРАТИВНОМУ
// вызывающему (`new CodeInputFieldCompat({...})`, `.value = ''`, `.error =
// true`) мост в Solid-дерево через сигналы. У нас вызывающий —
// `AuthCodeCard.solid.tsx`, САМ Solid-компонент: `value`/`error`/`disabled`
// передаются реактивными пропами напрямую, мост не нужен. Заодно `value`
// здесь — ПОЛНОСТЬЮ управляемый проп (`value`/`onChange`), а не опциональный
// `valueSignal` — carrier-сигнал оригинала бридж-класса тоже был нужен только
// императивному вызывающему.
import { createSignal, Index, Show, type JSX } from 'solid-js'
import classNames from '@helpers/string/classNames'
import { subscribeOn } from '@helpers/solid/subscribeOn'
import { Transition } from '@vendor/solid-transition-group'
import styles from './CodeInput.module.scss'

export type CodeInputSolidProps = {
  length: number
  value: string
  onChange: (v: string) => void
  onComplete: (code: string) => void
  error?: boolean
  /** идёт отправка — ячейки гаснут, инпут не кликается (tweb `.disabled`) */
  disabled?: boolean
  onFocusChange?: (focused: boolean) => void
  /** доп. класс на `.wrap` — карточка кода вешает `.codeInputField` (margin-top) */
  class?: string
  ref?: (el: HTMLInputElement) => void
}

export default function CodeInput(props: CodeInputSolidProps): JSX.Element {
  const [activeIndexStart, setActiveIndexStart] = createSignal(-1)
  const [activeIndexEnd, setActiveIndexEnd] = createSignal(-1)
  const [isInserting, setIsInserting] = createSignal(false)

  let isFocused = false
  let isShiftKeyDown = false
  const previousSelection = {
    inserting: false as boolean,
    start: null as number | null,
    end: null as number | null,
  }

  const syncSelection = (sel: {
    start: number | null
    end: number | null
    inserting: boolean
    originalStart: number | null
    originalEnd: number | null
  }) => {
    previousSelection.inserting = sel.inserting
    previousSelection.start = sel.originalStart
    previousSelection.end = sel.originalEnd
    if (sel.start === null || sel.end === null) {
      setActiveIndexStart(-1)
      setActiveIndexEnd(-1)
      return
    }
    setActiveIndexStart(sel.start)
    setActiveIndexEnd(sel.end)
  }

  let inputRef!: HTMLInputElement

  // Порт tweb `onSelectionChange`: нормализует выделение инпута к ширине в
  // один символ и переносит его в индексы подсвеченных ячеек.
  const onSelectionChange = (inputType?: string) => {
    if (
      !isFocused ||
      inputRef.ownerDocument.activeElement !== inputRef ||
      inputRef.selectionStart === null ||
      inputRef.selectionEnd === null
    ) {
      syncSelection({
        start: null,
        end: null,
        inserting: false,
        originalStart: inputRef.selectionStart,
        originalEnd: inputRef.selectionEnd,
      })
      setIsInserting(false)
      return
    }

    const maxLength = props.length
    const inserting = inputRef.value.length < maxLength && inputRef.selectionStart === inputRef.value.length
    setIsInserting(inserting)

    if (inserting || inputRef.selectionStart !== inputRef.selectionEnd) {
      syncSelection({
        start: inputRef.selectionStart,
        end: inserting ? inputRef.selectionEnd + 1 : inputRef.selectionEnd,
        inserting,
        originalStart: inputRef.selectionStart,
        originalEnd: inputRef.selectionEnd,
      })
      return
    }

    let selectionStart = 0
    let selectionEnd = 0
    let direction: 'forward' | 'backward' | undefined
    if (inputRef.selectionStart === 0) {
      selectionStart = 0
      selectionEnd = 1
      direction = 'forward'
    } else if (inputRef.selectionStart === maxLength) {
      selectionStart = maxLength - 1
      selectionEnd = maxLength
      direction = 'backward'
    } else {
      let startOffset = 0
      let endOffset = 1
      if (previousSelection.start !== null && previousSelection.end !== null) {
        const navigatedBackwards =
          inputRef.selectionStart < previousSelection.end &&
          Math.abs(previousSelection.start - previousSelection.end) === 1
        direction = navigatedBackwards ? 'backward' : 'forward'
        if (
          (navigatedBackwards && !previousSelection.inserting && inputType !== 'deleteContentForward') ||
          (!navigatedBackwards && isShiftKeyDown)
        ) {
          startOffset += -1
        }
      }
      if (isShiftKeyDown && inputType === undefined) endOffset += 1
      selectionStart = inputRef.selectionStart + startOffset
      selectionEnd = inputRef.selectionEnd + startOffset + endOffset
    }

    inputRef.setSelectionRange(selectionStart, selectionEnd, direction)
    syncSelection({
      start: selectionStart,
      end: selectionEnd,
      inserting,
      originalStart: inputRef.selectionStart,
      originalEnd: inputRef.selectionEnd,
    })
  }

  // tweb слушает `selectionchange` на документе — только так ловятся стрелки
  // и мышиное выделение внутри инпута. `subscribeOn` снимает слушатель сам
  // при размонтировании (onCleanup внутри).
  subscribeOn(document)('selectionchange', () => onSelectionChange())

  const handleInput: JSX.EventHandler<HTMLInputElement, InputEvent> = (e) => {
    const input = e.currentTarget
    const rawValue = input.value
    const oldValue = props.value
    const selectionSize = Math.abs((previousSelection.start ?? 0) - (previousSelection.end ?? 0))

    let finalValue = rawValue
    if (previousSelection.inserting || selectionSize === oldValue.length) {
      finalValue = finalValue.replace(/\D/g, '')
    }
    finalValue = finalValue.slice(0, props.length)

    const hasInvalidChars = !/^\d*$/.test(finalValue)
    if ((rawValue.length !== 0 && finalValue.length === 0) || finalValue === oldValue || hasInvalidChars) {
      input.value = oldValue
      if (hasInvalidChars) input.setSelectionRange(previousSelection.start ?? 0, previousSelection.end ?? 0)
      return
    }

    if (finalValue.length < oldValue.length) onSelectionChange(e.inputType)

    props.onChange(finalValue)
    if (finalValue.length === props.length) props.onComplete(finalValue)
  }

  return (
    <div class={classNames(styles.wrap, props.error && styles.error, props.disabled && styles.disabled, props.class)}>
      <input
        ref={(el) => {
          inputRef = el
          props.ref?.(el)
        }}
        class={styles.input}
        inputMode="numeric"
        autocomplete="one-time-code"
        required
        spellcheck={false}
        pattern="^\d*$"
        value={props.value}
        disabled={props.disabled}
        onFocus={() => {
          inputRef.setSelectionRange(props.value.length, props.value.length)
          isFocused = true
          props.onFocusChange?.(true)
          onSelectionChange()
        }}
        onBlur={() => {
          isFocused = false
          props.onFocusChange?.(false)
          onSelectionChange()
        }}
        onKeyDown={(e) => {
          if (e.key === 'Shift') isShiftKeyDown = true
        }}
        onKeyUp={(e) => {
          if (e.key === 'Shift') isShiftKeyDown = false
        }}
        onInput={handleInput}
      />

      <Index each={Array.from({ length: props.length })}>
        {(_, idx) => (
          <div class={classNames(styles.digit, activeIndexStart() <= idx && idx < activeIndexEnd() && styles.active)}>
            <Transition>
              <Show when={props.value[idx]}>
                <div class={styles.digitContent}>{props.value[idx]}</div>
              </Show>
            </Transition>
            {isInserting() && props.value.length === idx && <div class={styles.caret} />}
          </div>
        )}
      </Index>
    </div>
  )
}

// web-client/src/components/auth/CodeInput.tsx
// CodeInput — ввод кода подтверждения единым полем (порт tweb
// `components/codeInputField.tsx`): ОДИН невидимый <input inputmode=numeric
// autocomplete=one-time-code> absolute поверх ряда отрисованных ячеек. Вставка
// строки из N цифр из буфера заполняет всё; автозаполнение из SMS работает.
//
// Подсветка ячейки считается по `selectionStart/selectionEnd`, как в оригинале:
// инпут принудительно держит выделение шириной в один символ
// (`setSelectionRange(start, end, direction)`), поэтому стрелки двигают рамку по
// ячейкам, а Shift+стрелки выделяют несколько. Каретка рисуется только в режиме
// дописывания (`isInserting`) и только в ячейке за последней цифрой.
//
// Цифра влетает translateY(20px)→0 spring-безье, при удалении — scale(.5)+fade.
// onFocusChange — для обезьянки TrackingMonkey (tweb вешает focus/blur на input).
import { useEffect, useRef, useState } from 'react'
import classNames from '../../shared/lib/classNames'
import s from './CodeInput.module.scss'

// Ячейка: держит последнюю цифру, чтобы при удалении сыграть exit-анимацию
// (tweb Transition s-exit-to: scale(.5)+fade) без framer.
function Digit({ digit }: { digit: string }) {
  const [leaving, setLeaving] = useState('')
  const prev = useRef(digit)
  if (prev.current !== digit) {
    if (prev.current && !digit) setLeaving(prev.current)
    prev.current = digit
  }
  return (
    <>
      {digit && <div key={digit} className={classNames(s.digitContent, s.enter)}>{digit}</div>}
      {!digit && leaving && (
        <div className={classNames(s.digitContent, s.exit)} onAnimationEnd={() => setLeaving('')}>
          {leaving}
        </div>
      )}
    </>
  )
}

export default function CodeInput({
  length,
  value,
  onChange,
  onComplete,
  error,
  disabled,
  onFocusChange,
  className = '',
}: {
  length: number
  value: string
  onChange: (v: string) => void
  onComplete: (code: string) => void
  error?: boolean
  /** идёт отправка — ячейки гаснут, инпут не кликается (tweb `.disabled`) */
  disabled?: boolean
  onFocusChange?: (focused: boolean) => void
  /** доп. класс на `.wrap` — карточка кода вешает `.codeInputField` (margin-top 1.5rem) */
  className?: string
}) {
  const inputRef = useRef<HTMLInputElement>(null)
  // Диапазон подсвеченных ячеек — [start, end) в терминах tweb activeIndex*.
  const [active, setActive] = useState<[number, number]>([-1, -1])
  const [isInserting, setIsInserting] = useState(false)

  const focusedRef = useRef(false)
  const shiftRef = useRef(false)
  // Предыдущее «сырое» выделение — по нему tweb определяет направление хода.
  const prevSel = useRef<{ inserting: boolean; start: number | null; end: number | null }>({
    inserting: false,
    start: null,
    end: null,
  })

  // Порт tweb `onSelectionChange`: нормализует выделение инпута к ширине в один
  // символ и переносит его в индексы подсвеченных ячеек.
  const syncSelection = (inputType?: string) => {
    const input = inputRef.current
    if (!input) return
    const remember = (
      start: number | null,
      end: number | null,
      inserting: boolean,
      originalStart: number | null,
      originalEnd: number | null,
    ) => {
      prevSel.current = { inserting, start: originalStart, end: originalEnd }
      const a = start === null || end === null ? -1 : start
      const b = start === null || end === null ? -1 : end
      setActive((p) => (p[0] === a && p[1] === b ? p : [a, b]))
    }

    if (
      !focusedRef.current ||
      document.activeElement !== input ||
      input.selectionStart === null ||
      input.selectionEnd === null
    ) {
      remember(null, null, false, input.selectionStart, input.selectionEnd)
      setIsInserting(false)
      return
    }

    const inserting = input.value.length < length && input.selectionStart === input.value.length
    setIsInserting(inserting)

    if (inserting || input.selectionStart !== input.selectionEnd) {
      remember(
        input.selectionStart,
        inserting ? input.selectionEnd + 1 : input.selectionEnd,
        inserting,
        input.selectionStart,
        input.selectionEnd,
      )
      return
    }

    let selectionStart = 0
    let selectionEnd = 0
    let direction: 'forward' | 'backward' | undefined
    if (input.selectionStart === 0) {
      selectionStart = 0
      selectionEnd = 1
      direction = 'forward'
    } else if (input.selectionStart === length) {
      selectionStart = length - 1
      selectionEnd = length
      direction = 'backward'
    } else {
      let startOffset = 0
      let endOffset = 1
      if (prevSel.current.start !== null && prevSel.current.end !== null) {
        const navigatedBackwards =
          input.selectionStart < prevSel.current.end &&
          Math.abs(prevSel.current.start - prevSel.current.end) === 1
        direction = navigatedBackwards ? 'backward' : 'forward'
        if (
          (navigatedBackwards && !prevSel.current.inserting && inputType !== 'deleteContentForward') ||
          (!navigatedBackwards && shiftRef.current)
        ) {
          startOffset += -1
        }
      }
      if (shiftRef.current && inputType === undefined) endOffset += 1
      selectionStart = input.selectionStart + startOffset
      selectionEnd = input.selectionEnd + startOffset + endOffset
    }

    input.setSelectionRange(selectionStart, selectionEnd, direction)
    remember(selectionStart, selectionEnd, inserting, input.selectionStart, input.selectionEnd)
  }

  // tweb слушает `selectionchange` на документе — только так ловятся стрелки и
  // мышиное выделение внутри инпута.
  const syncRef = useRef(syncSelection)
  syncRef.current = syncSelection
  useEffect(() => {
    const handler = () => syncRef.current()
    document.addEventListener('selectionchange', handler)
    return () => document.removeEventListener('selectionchange', handler)
  }, [])

  // Значение приходит сверху (карточка сбрасывает его на ошибке), а React
  // пишет его в DOM уже после коммита — пересчитываем подсветку по факту.
  useEffect(() => {
    syncRef.current()
  }, [value])

  // На время отправки поле гаснет и теряет фокус; после ответа сервера tweb
  // возвращает его обратно (`fastRaf(() => codeInputField.input.focus())`).
  const wasFocused = useRef(false)
  useEffect(() => {
    if (disabled) {
      wasFocused.current = focusedRef.current
      return
    }
    if (!wasFocused.current) return
    wasFocused.current = false
    inputRef.current?.focus()
  }, [disabled])

  const handleInput = (e: React.ChangeEvent<HTMLInputElement>) => {
    const input = e.currentTarget
    const raw = input.value
    const inputType = (e.nativeEvent as InputEvent).inputType
    const selectionSize = Math.abs((prevSel.current.start ?? 0) - (prevSel.current.end ?? 0))

    let next = raw
    if (prevSel.current.inserting || selectionSize === value.length) next = next.replace(/\D/g, '')
    next = next.slice(0, length)

    const hasInvalid = !/^\d*$/.test(next)
    if ((raw.length !== 0 && next.length === 0) || next === value || hasInvalid) {
      input.value = value
      if (hasInvalid) input.setSelectionRange(prevSel.current.start ?? 0, prevSel.current.end ?? 0)
      return
    }

    if (next.length < value.length) syncSelection(inputType)

    onChange(next)
    if (next.length === length) onComplete(next)
  }

  return (
    <div
      className={classNames(s.wrap, error ? s.error : '', disabled ? s.disabled : '', className)}
    >
      <input
        ref={inputRef}
        className={s.input}
        inputMode="numeric"
        autoComplete="one-time-code"
        spellCheck={false}
        pattern="^\d*$"
        required
        disabled={disabled}
        autoFocus
        value={value}
        onChange={handleInput}
        onFocus={(e) => {
          e.target.setSelectionRange(value.length, value.length)
          focusedRef.current = true
          onFocusChange?.(true)
          syncSelection()
        }}
        onBlur={() => {
          focusedRef.current = false
          onFocusChange?.(false)
          syncSelection()
        }}
        onKeyDown={(e) => {
          if (e.key === 'Shift') shiftRef.current = true
        }}
        onKeyUp={(e) => {
          if (e.key === 'Shift') shiftRef.current = false
        }}
      />
      {Array.from({ length }).map((_, i) => (
        <div
          key={i}
          className={classNames(s.digit, active[0] <= i && i < active[1] ? s.active : '')}
        >
          <Digit digit={value[i] ?? ''} />
          {isInserting && value.length === i && <div className={s.caret} />}
        </div>
      ))}
    </div>
  )
}
