// web-client/src/components/auth/cards/EmailRecoverCard.solid.tsx
/** @jsxImportSource solid-js */
// EmailRecoverCard — восстановление доступа кодом с привязанной почты
// (Solid-порт нашей React `cards/EmailRecoverCard.tsx`, которая сама — порт
// tweb `pages/cards/EmailRecoverCard.tsx`, 92 строки). Сюда ведёт «Forgot
// Password?» с карточки облачного пароля (`PasswordCard.solid.tsx`).
//
// Дерево 1:1 с живым tweb (dom-референс §2.6 нашей React-версии):
//
//   div.card                                    ← БЕЗ page-модификатора (его нет и в scss tweb)
//     div
//       div.sticker[--sticker-size: 130px] > div.lottie[--size] > canvas.lottie
//       div.title.text-center.text-overflow-wrap > span.i18n
//       div.subtitle.text-center > span.i18n > br + b > span.bluff-spoiler…
//     div.input-wrapper
//       div.wrap (поле кода — ШЕСТЬ ячеек, ВНУТРИ input-wrapper, БЕЗ .codeInputField)
//       div.errorLabel
//       button.btn-primary.btn-secondary.btn-primary-transparent.primary.rp
//
// Кнопки «Далее» тут нет: код уходит на сервер, как только набрана последняя
// цифра (`onComplete` у `CodeInput`). Повторной отправки тут тоже нет — у tweb
// EmailRecoverCard ровно два действия: подтвердить код и «Cancel» →
// `navigate({name:'password'})`. Единственный путь к повтору — вернуться на
// карточку пароля и нажать «Forgot Password?» ещё раз.
//
// ── Cancel несёт ВСЮ нагрузку password, а не только token ───────────────────
// У tweb Cancel ничего не передаёт — карточка `password` там перечитывает
// общий `authState`. У нас переход обязан довезти нагрузку САМ
// (`authFlow.solid.tsx::CardPayloadMap.password`), поэтому Cancel собирает её
// из СВОЕГО `props.spec.payload` (`token`/`hint`/`emailPattern`) — это и есть
// закрытие долга задачи 4 (находка 1 ревью, разбор — докблок
// `PasswordCard.solid.tsx`): маска возвращается пропом, не модульным Map.
import { createSignal, type JSX } from 'solid-js'
import Button from '@components/buttonTsx.solid'
import { i18n, type LangPackKey } from '@lib/langPack'
import AuthCard from '../AuthCard.solid'
import MediaHeader from '../MediaHeader.solid'
import CodeInput from '../CodeInput.solid'
import EmailPattern from '../emailPattern.solid'
import { useAuthFlow, type CardSpec } from '../authFlow.solid'
import styles from '../AuthFlow.module.scss'

type Spec = Extract<CardSpec, { name: 'emailRecover' }>

// tweb mediaSizes.isMobile ? 100 : 130 — тот же выбор, что у AuthCodeCard/PasswordCard.
const STICKER_SIZE = 130

// tweb CodeInputFieldCompat({length: 6}) — на этой карточке код ШЕСТИзначный
// (у AuthCodeCard — пять; сервер восстановления шлёт более длинный код).
const CODE_LEN = 6

export default function EmailRecoverCard(props: { spec: Spec }): JSX.Element {
  const { managers, navigate, toIm } = useAuthFlow()
  const token = () => props.spec.payload.token
  const emailPattern = () => props.spec.payload.emailPattern
  const hint = () => props.spec.payload.hint

  const [error, setError] = createSignal<LangPackKey | ''>('')
  const [busy, setBusy] = createSignal(false)
  const [code, setCode] = createSignal('')

  const errorLabel = () => {
    const key = error()
    return key ? i18n(key) : ''
  }

  const submit = async (value: string) => {
    if (busy()) return
    setError('')
    setBusy(true)
    const res = await managers.auth.confirmPasswordRecovery(token(), value, 'web', 'browser')
    setBusy(false)
    if ('user' in res) {
      void toIm()
      return
    }
    setCode('')
    setError(
      res.error === 'invalid_code'
        ? 'PHONE_CODE_INVALID'
        // Сервер не различает истёкший код и исчерпанные попытки — ни то ни
        // другое уже не поправить вводом, обе ветки просят начать заново.
        : res.error === 'recovery_expired'
          ? 'Login.Code.Expired'
          : 'Login.Error.Generic',
    )
  }

  const cancel = () => {
    navigate({ name: 'password', payload: { token: token(), hint: hint(), emailPattern: emailPattern() } })
  }

  return (
    <AuthCard
      header={
        <MediaHeader>
          <MediaHeader.Sticker size={STICKER_SIZE} name="Mailbox" />
          <MediaHeader.Title>{i18n('Login.ResetPassword.Title')}</MediaHeader.Title>
          {/* без .secondary — подзаголовок этой карточки в tweb белый */}
          <MediaHeader.Subtitle>
            {i18n('Login.ResetPassword.CodeHint')}
            <br />
            <EmailPattern pattern={emailPattern()} />
          </MediaHeader.Subtitle>
        </MediaHeader>
      }
    >
      <CodeInput
        length={CODE_LEN}
        value={code()}
        onChange={(v) => {
          setError('')
          setCode(v)
        }}
        onComplete={(v) => void submit(v)}
        error={!!error()}
        disabled={busy()}
      />

      {/* высота зарезервирована всегда — появление ошибки не двигает раскладку */}
      <div class={styles.errorLabel}>{errorLabel()}</div>

      <Button
        class="btn-primary btn-secondary btn-primary-transparent primary"
        disabled={busy()}
        onClick={cancel}
        text="Cancel"
      />
    </AuthCard>
  )
}

// web-client/src/components/auth/cards/EmailRecoverCard.tsx
// EmailRecoverCard — восстановление доступа кодом с привязанной почты (порт
// карточки tweb `pages/cards/EmailRecoverCard.tsx`). Сюда ведёт ссылка
// «Forgot Password?» с карточки облачного пароля.
//
// Дерево 1:1 с живым tweb (dom-референс §2.6):
//
//   div.card                                    ← БЕЗ page-модификатора (его нет и в scss tweb)
//     div
//       div.sticker[--sticker-size: 130px] > div.lottie[--size] > canvas.lottie
//       div.title.text-center.text-overflow-wrap > span.i18n
//       div.subtitle.text-center > span.i18n > br + b > span.bluff-spoiler…
//     div.input-wrapper
//       div.wrap (поле кода — ШЕСТЬ ячеек и ВНУТРИ input-wrapper, БЕЗ .codeInputField)
//       div.errorLabel
//       button.btn-primary.btn-secondary.btn-primary-transparent.primary.rp
//
// Кнопки «Далее» тут нет: код уходит на сервер, как только набрана последняя цифра.
// Повторной отправки тут тоже нет — в `EmailRecoverCard.tsx` у tweb ровно два
// действия: `onFill` (подтвердить код) и «Cancel» → `navigate({name:'password'})`.
// Единственный путь к повтору — вернуться на карточку пароля и нажать «Forgot
// Password?» ещё раз; та ссылка в tweb каждый раз идёт на сервер (см. AuthFlow).
import { useState } from 'react'
import { useT } from '../../../i18n'
import { useManagers } from '../../../core/hooks/useManagers'
import MediaHeader from '../MediaHeader'
import CodeInput from '../CodeInput'
import EmailPattern from '../emailPattern'
import { SecondaryButton } from '../AuthButton'
import s from '../AuthFlow.module.scss'

export interface EmailRecoverCardProps {
  /** одноразовый токен из sign_in — им же подтверждается код с почты */
  token: string
  /** маска адреса с сервера, напр. `d****@e******.com` */
  emailPattern: string
  /** «Cancel» — назад на карточку облачного пароля */
  onCancel: () => void
  /** вход завершён */
  onComplete: () => void
}

// tweb mediaSizes.isMobile ? 100 : 130
const STICKER_SIZE = 130

// tweb CodeInputFieldCompat({length: 6}) — на этой карточке код ШЕСТИзначный.
const CODE_LEN = 6

export default function EmailRecoverCard({
  token,
  emailPattern,
  onCancel,
  onComplete,
}: EmailRecoverCardProps) {
  const t = useT()
  const managers = useManagers()

  const [error, setError] = useState('')
  const [busy, setBusy] = useState(false)
  const [code, setCode] = useState('')

  const submit = async (value: string) => {
    if (busy) return
    setError('')
    setBusy(true)
    const res = await managers.auth.confirmPasswordRecovery(token, value, 'web', 'browser')
    if ('user' in res) {
      onComplete()
      return
    }
    setBusy(false)
    setCode('')
    setError(
      res.error === 'invalid_code'
        ? t('PHONE_CODE_INVALID')
        // Сервер не различает истёкший код и исчерпанные 5 попыток — ни то ни
        // другое уже не поправить вводом, обе ветки просят начать заново.
        : res.error === 'recovery_expired'
          ? t('Login.Code.Expired')
          : t('Login.Error.Generic'),
    )
  }

  return (
    <div className={s.card}>
      <MediaHeader>
        <MediaHeader.Sticker size={STICKER_SIZE} name="Mailbox" />
        <MediaHeader.Title>
          <span className="i18n">{t('Login.ResetPassword.Title')}</span>
        </MediaHeader.Title>
        {/* без `.secondary` — подзаголовок этой карточки в tweb белый */}
        <MediaHeader.Subtitle>
          <span className="i18n">
            {t('Login.ResetPassword.CodeHint')}
            <br />
            <EmailPattern pattern={emailPattern} />
          </span>
        </MediaHeader.Subtitle>
      </MediaHeader>

      <div className="input-wrapper">
        {/* без `s.codeInputField`: у этой карточки поле идёт вплотную к гриду —
            в самом tweb класс сюда не передан (см. §9 dom-референса). */}
        <CodeInput
          length={CODE_LEN}
          value={code}
          onChange={(v) => {
            setError('')
            setCode(v)
          }}
          onComplete={(v) => void submit(v)}
          error={!!error}
          disabled={busy}
        />

        {/* высота зарезервирована всегда — появление ошибки не двигает раскладку */}
        <div className={s.errorLabel}>{error}</div>

        <SecondaryButton onClick={onCancel}>{t('Cancel')}</SecondaryButton>
      </div>
    </div>
  )
}
