// web-client/src/components/sidebarLeft/pendingSuggestionItem.solid.tsx
/** @jsxImportSource solid-js */
// Порт tweb `src/components/sidebarLeft/pendingSuggestionItem.tsx` (812502980,
// 1-86) — строка плашки-подсказки (`Row` с крестиком) и её простой вид
// `SimpleSuggestion`; в свёрнутой колонке вместо строки — квадрат с одним
// эмодзи (`useIsSidebarCollapsed`).
//
// Эталон DOM (живой tweb, плашка «Never miss a message!»):
//   div.rp.row.row-clickable.hover-effect._suggestion._secondary
//     > button.btn-icon.close._close + div.row-title > span.text-bold._suggestionTitle
//     + div.row-subtitle > span._suggestionSubtitle
//
// Расхождение с оригиналом одно: у `SimpleSuggestion` нет пропа `danger`
// (класс `.danger`, `color: 'danger'`, `hover-danger-effect`). Его зовёт
// единственный вид — «аккаунт заморожен» (`frozenSuggestion.tsx`), а заморозки
// на бэкенде нет (О-108 волна 7); ветка без вызывающего — мёртвый код.
import { Show, type JSX } from 'solid-js'
import Button from '@components/buttonTsx.solid'
import RippleElement from '@components/rippleElement.solid'
import Row from '@components/rowTsx.solid'
import styles from '@components/sidebarLeft/pendingSuggestion.module.scss'
import cancelEvent from '@helpers/dom/cancelEvent'
import documentFragmentToNodes from '@helpers/dom/documentFragmentToNodes'
import classNames from '@helpers/string/classNames'
import I18n from '@lib/langPack'
import wrapEmojiText from '@lib/richtext/wrapEmojiText'
import { useIsSidebarCollapsed } from '@stores/foldersSidebar.solid'

export const PendingSuggestion = (props: Parameters<typeof Row>[0] & { closable?: () => void }) => {
  return (
    <Row
      {...props}
      class={classNames(styles.suggestion, props.class)}
    >
      {props.children}
      {props.closable && (
        <Button.Icon
          icon="close"
          class={styles.close}
          aria-label={I18n.format('Close', true)}
          onClick={(e) => {
            cancelEvent(e)
            props.closable!()
          }}
        />
      )}
    </Row>
  )
}

PendingSuggestion.Title = (props: Parameters<typeof Row.Title>[0]) => {
  return (
    <Row.Title {...props}>
      <span class={classNames('text-bold', styles.suggestionTitle)}>{props.children}</span>
    </Row.Title>
  )
}

PendingSuggestion.Subtitle = (props: Parameters<typeof Row.Subtitle>[0]) => {
  return (
    <Row.Subtitle {...props}>
      <span class={styles.suggestionSubtitle}>{props.children}</span>
    </Row.Subtitle>
  )
}

export function SimpleSuggestion(props: {
  emoji: string | (() => DocumentFragment)
  title: JSX.Element
  subtitle: JSX.Element
  onClick: () => void
  onClose?: () => void
}) {
  const [isSidebarCollapsed] = useIsSidebarCollapsed()
  const emoji = typeof(props.emoji) === 'string' ? () => wrapEmojiText(props.emoji as string) : props.emoji

  return (
    <Show
      when={isSidebarCollapsed()}
      fallback={
        <PendingSuggestion
          class={styles.secondary}
          clickable={props.onClick}
          closable={props.onClose}
        >
          <PendingSuggestion.Title>{props.title}</PendingSuggestion.Title>
          <PendingSuggestion.Subtitle>{props.subtitle}</PendingSuggestion.Subtitle>
        </PendingSuggestion>
      }
    >
      <RippleElement
        component="div"
        class={classNames(styles.collapsed, 'hover-effect')}
        onClick={props.onClick}
      >
        {documentFragmentToNodes(emoji())}
      </RippleElement>
    </Show>
  )
}

// web-client/src/components/sidebarLeft/pendingSuggestionItem.tsx
// Порт tweb `src/components/sidebarLeft/pendingSuggestionItem.tsx`.
//
// Разметка снята с живого tweb (localhost:8099, плашка «Never miss a message!»):
//   div.rp.row.row-clickable.hover-effect._suggestion._secondary
//     > div.c-ripple
//     + button.btn-icon.close._close.rp > div.c-ripple + span.tgico.button-icon
//     + div[dir=auto].row-title    > span.text-bold > текст
//     + div[dir=auto].row-subtitle > span._suggestionSubtitle > текст
// В свёрнутом сайдбаре вместо строки — квадрат с одним эмодзи (tweb Show/fallback).
//
// Отступления от tweb:
//   • у tweb это `<Row>` + `<Button.Icon>` из его компонентной библиотеки; у нас
//     `.row`-классы проставляются вручную (как в ChatListItem) и крестик — наш
//     `IconButton` (он и есть порт `ButtonIcon`);
//   • эмодзи — обычный текст, а не `wrapEmojiText` (подсистемы замены эмодзи на
//     спрайты у нас нет).
import type { ReactNode } from 'react'
import classNames from '../../shared/lib/classNames'
import { useRipple } from '../../shared/ui/Ripple/useRipple'
import IconButton from '../../shared/ui/IconButton'
import TgIcon from '../TgIcon'
import s from './pendingSuggestion.module.scss'

export function SimpleSuggestion({
  emoji,
  title,
  subtitle,
  collapsed,
  onClick,
  onClose,
}: {
  emoji: string
  title: ReactNode
  subtitle: ReactNode
  /** сайдбар свёрнут в узкую полосу (tweb useIsSidebarCollapsed) */
  collapsed?: boolean
  onClick: () => void
  onClose?: () => void
}) {
  const { onPointerDown, ripple } = useRipple()

  if (collapsed) {
    return (
      <div
        className={classNames('rp', 'hover-effect', s.collapsed)}
        onPointerDown={onPointerDown}
        onClick={onClick}
      >
        {ripple}
        {emoji}
      </div>
    )
  }

  return (
    <div
      className={classNames('rp', 'row', 'row-clickable', 'hover-effect', s.secondary)}
      onPointerDown={onPointerDown}
      onClick={onClick}
    >
      {ripple}
      {onClose && (
        <IconButton
          className={classNames('close', s.close)}
          tabIndex={-1}
          onClick={(e) => {
            // tweb cancelEvent — клик по крестику не должен поднять onClick строки
            e.preventDefault()
            e.stopPropagation()
            onClose()
          }}
        >
          {/* tweb: span.tgico.button-icon; размер глифа берётся из font-size кнопки */}
          <TgIcon name="close" className="button-icon" size="inherit" />
        </IconButton>
      )}
      <div dir="auto" className="row-title">
        <span className={classNames('text-bold', s.suggestionTitle)}>{title}</span>
      </div>
      <div dir="auto" className="row-subtitle">
        <span className={s.suggestionSubtitle}>{subtitle}</span>
      </div>
    </div>
  )
}
